package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Aspirante generated by hbm2java
 */
public class Aspirante  implements java.io.Serializable {


     private Usuario cedula;
     private Plantel plantel;
     private String nivelingreso;
     private Integer horastrabajo;
     private String beca;
     private Integer hermanosuniv;
     private String servicios;
     private String actividadextr;
     private String materiasfalla;
     private String dependenciaeco;
     private String habitosestudio;
     private BigDecimal promedio;
     private String sexo;
     private Boolean borrado;
     private Set<Estudianterepresentante> estudianterepresentantes = new HashSet<Estudianterepresentante>(0);

    public Aspirante() {
    }

	
    public Aspirante(Usuario usuario) {
        this.cedula = usuario;
        
    }
    public Aspirante(Usuario cedula, Plantel plantel, String nivelingreso, Integer horastrabajo, String beca, Integer hermanosuniv, String servicios, String actividadextr, String materiasfalla, String dependenciaeco, String habitosestudio, BigDecimal promedio, String sexo, Boolean borrado, Set<Estudianterepresentante> estudianterepresentantes, Set<Preinscrito> preinscritos) {
       this.cedula = cedula;
       this.plantel = plantel;
       this.nivelingreso = nivelingreso;
       this.horastrabajo = horastrabajo;
       this.beca = beca;
       this.hermanosuniv = hermanosuniv;
       this.servicios = servicios;
       this.actividadextr = actividadextr;
       this.materiasfalla = materiasfalla;
       this.dependenciaeco = dependenciaeco;
       this.habitosestudio = habitosestudio;
       this.promedio = promedio;
       this.sexo = sexo;
       this.borrado = borrado;
       this.estudianterepresentantes = estudianterepresentantes;
    }
   
    public Usuario getCedula() {
        return this.cedula;
    }
    
    public void setCedula(Usuario cedula) {
        this.cedula = cedula;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    
    public String getNivelingreso() {
        return this.nivelingreso;
    }
    
    public void setNivelingreso(String nivelingreso) {
        this.nivelingreso = nivelingreso;
    }
    public Integer getHorastrabajo() {
        return this.horastrabajo;
    }
    
    public void setHorastrabajo(Integer horastrabajo) {
        this.horastrabajo = horastrabajo;
    }
    public String getBeca() {
        return this.beca;
    }
    
    public void setBeca(String beca) {
        this.beca = beca;
    }
    public Integer getHermanosuniv() {
        return this.hermanosuniv;
    }
    
    public void setHermanosuniv(Integer hermanosuniv) {
        this.hermanosuniv = hermanosuniv;
    }
    public String getServicios() {
        return this.servicios;
    }
    
    public void setServicios(String servicios) {
        this.servicios = servicios;
    }
    public String getActividadextr() {
        return this.actividadextr;
    }
    
    public void setActividadextr(String actividadextr) {
        this.actividadextr = actividadextr;
    }
    public String getMateriasfalla() {
        return this.materiasfalla;
    }
    
    public void setMateriasfalla(String materiasfalla) {
        this.materiasfalla = materiasfalla;
    }
    public String getDependenciaeco() {
        return this.dependenciaeco;
    }
    
    public void setDependenciaeco(String dependenciaeco) {
        this.dependenciaeco = dependenciaeco;
    }
    public String getHabitosestudio() {
        return this.habitosestudio;
    }
    
    public void setHabitosestudio(String habitosestudio) {
        this.habitosestudio = habitosestudio;
    }
    public BigDecimal getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(BigDecimal promedio) {
        this.promedio = promedio;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Estudianterepresentante> getEstudianterepresentantes() {
        return this.estudianterepresentantes;
    }
    
    public void setEstudianterepresentantes(Set<Estudianterepresentante> estudianterepresentantes) {
        this.estudianterepresentantes = estudianterepresentantes;
    }
    




}


