package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Aspirante generated by hbm2java
 */
public class Aspirante  implements java.io.Serializable {


     private String cedula;
     private Plantel plantel;
     private Usuario usuario;
     private String representante;
     private String nivelIngreso;
     private Integer horasTrabajo;
     private String beca;
     private Integer hermanosUniv;
     private String servicios;
     private String actividadExtr;
     private String materiasFalla;
     private String dependenciaEco;
     private String habitosEstudio;
     private BigDecimal promedio;
     private Boolean borrado;
     private Set<EstudianteRepresentante> estudianteRepresentantes = new HashSet<EstudianteRepresentante>(0);
     private Set<Preinscrito> preinscritos = new HashSet<Preinscrito>(0);

    public Aspirante() {
    }

	
    public Aspirante(String cedula, Usuario usuario) {
        this.cedula = cedula;
        this.usuario = usuario;
    }
    public Aspirante(String cedula, Plantel plantel, Usuario usuario, String representante, String nivelIngreso, Integer horasTrabajo, String beca, Integer hermanosUniv, String servicios, String actividadExtr, String materiasFalla, String dependenciaEco, String habitosEstudio, BigDecimal promedio, Boolean borrado, Set<EstudianteRepresentante> estudianteRepresentantes, Set<Preinscrito> preinscritos) {
       this.cedula = cedula;
       this.plantel = plantel;
       this.usuario = usuario;
       this.representante = representante;
       this.nivelIngreso = nivelIngreso;
       this.horasTrabajo = horasTrabajo;
       this.beca = beca;
       this.hermanosUniv = hermanosUniv;
       this.servicios = servicios;
       this.actividadExtr = actividadExtr;
       this.materiasFalla = materiasFalla;
       this.dependenciaEco = dependenciaEco;
       this.habitosEstudio = habitosEstudio;
       this.promedio = promedio;
       this.borrado = borrado;
       this.estudianteRepresentantes = estudianteRepresentantes;
       this.preinscritos = preinscritos;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public String getNivelIngreso() {
        return this.nivelIngreso;
    }
    
    public void setNivelIngreso(String nivelIngreso) {
        this.nivelIngreso = nivelIngreso;
    }
    public Integer getHorasTrabajo() {
        return this.horasTrabajo;
    }
    
    public void setHorasTrabajo(Integer horasTrabajo) {
        this.horasTrabajo = horasTrabajo;
    }
    public String getBeca() {
        return this.beca;
    }
    
    public void setBeca(String beca) {
        this.beca = beca;
    }
    public Integer getHermanosUniv() {
        return this.hermanosUniv;
    }
    
    public void setHermanosUniv(Integer hermanosUniv) {
        this.hermanosUniv = hermanosUniv;
    }
    public String getServicios() {
        return this.servicios;
    }
    
    public void setServicios(String servicios) {
        this.servicios = servicios;
    }
    public String getActividadExtr() {
        return this.actividadExtr;
    }
    
    public void setActividadExtr(String actividadExtr) {
        this.actividadExtr = actividadExtr;
    }
    public String getMateriasFalla() {
        return this.materiasFalla;
    }
    
    public void setMateriasFalla(String materiasFalla) {
        this.materiasFalla = materiasFalla;
    }
    public String getDependenciaEco() {
        return this.dependenciaEco;
    }
    
    public void setDependenciaEco(String dependenciaEco) {
        this.dependenciaEco = dependenciaEco;
    }
    public String getHabitosEstudio() {
        return this.habitosEstudio;
    }
    
    public void setHabitosEstudio(String habitosEstudio) {
        this.habitosEstudio = habitosEstudio;
    }
    public BigDecimal getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(BigDecimal promedio) {
        this.promedio = promedio;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<EstudianteRepresentante> getEstudianteRepresentantes() {
        return this.estudianteRepresentantes;
    }
    
    public void setEstudianteRepresentantes(Set<EstudianteRepresentante> estudianteRepresentantes) {
        this.estudianteRepresentantes = estudianteRepresentantes;
    }
    public Set<Preinscrito> getPreinscritos() {
        return this.preinscritos;
    }
    
    public void setPreinscritos(Set<Preinscrito> preinscritos) {
        this.preinscritos = preinscritos;
    }




}


