package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private String lugar;
     private Integer capacidad;
     private String implementos;
     private Boolean borrado;
     private Set<Examen> examens = new HashSet<Examen>(0);
     private Set<Clase> clases = new HashSet<Clase>(0);

    public Aula() {
    }

	
    public Aula(String lugar) {
        this.lugar = lugar;
    }
    public Aula(String lugar, Integer capacidad, String implementos, Boolean borrado, Set<Examen> examens, Set<Clase> clases) {
       this.lugar = lugar;
       this.capacidad = capacidad;
       this.implementos = implementos;
       this.borrado = borrado;
       this.examens = examens;
       this.clases = clases;
    }
   
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public String getImplementos() {
        return this.implementos;
    }
    
    public void setImplementos(String implementos) {
        this.implementos = implementos;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }
    public Set<Clase> getClases() {
        return this.clases;
    }
    
    public void setClases(Set<Clase> clases) {
        this.clases = clases;
    }




}


