package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String descripcion;
     private Boolean borrado;
     private Set<Preinscritocarrera> preinscritocarreras = new HashSet<Preinscritocarrera>(0);

    public Carrera() {
    }

	
    public Carrera(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Carrera(String codigo, String nombre, String descripcion, Boolean borrado, Set<Preinscritocarrera> preinscritocarreras) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.borrado = borrado;
       this.preinscritocarreras = preinscritocarreras;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Preinscritocarrera> getPreinscritocarreras() {
        return this.preinscritocarreras;
    }
    
    public void setPreinscritocarreras(Set<Preinscritocarrera> preinscritocarreras) {
        this.preinscritocarreras = preinscritocarreras;
    }




}


