package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Catedra generated by hbm2java
 */
public class Catedra  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String descripcion;
     private Boolean borrado;
     private Set<Clase> clases = new HashSet<Clase>(0);
     private Set<ProfesorMateria> profesorMaterias = new HashSet<ProfesorMateria>(0);

    public Catedra() {
    }

	
    public Catedra(String codigo) {
        this.codigo = codigo;
    }
    public Catedra(String codigo, String nombre, String descripcion, Boolean borrado, Set<Clase> clases, Set<ProfesorMateria> profesorMaterias) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.borrado = borrado;
       this.clases = clases;
       this.profesorMaterias = profesorMaterias;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Clase> getClases() {
        return this.clases;
    }
    
    public void setClases(Set<Clase> clases) {
        this.clases = clases;
    }
    public Set<ProfesorMateria> getProfesorMaterias() {
        return this.profesorMaterias;
    }
    
    public void setProfesorMaterias(Set<ProfesorMateria> profesorMaterias) {
        this.profesorMaterias = profesorMaterias;
    }




}


