package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Catedra generated by hbm2java
 */
public class Catedra  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String descripcion;
     private Boolean borrado;
     

    public Catedra() {
    }

	
    public Catedra(String codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }
    public Catedra(String codigo, String nombre, String descripcion, Boolean borrado) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.borrado = borrado;
       
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    




}


