package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA



/**
 * Charlaplantel generated by hbm2java
 */
public class Charlaplantel  implements java.io.Serializable {


     private int id;
     private Estudiantesc estudiantesc;
     private Plantel plantel;
     private String fecha;
     private Boolean borrado;

    public Charlaplantel() {
    }

	
    public Charlaplantel(int id) {
        this.id = id;
    }
    public Charlaplantel(int id, Estudiantesc estudiantesc, Plantel plantel, String fecha, Boolean borrado) {
       this.id = id;
       this.estudiantesc = estudiantesc;
       this.plantel = plantel;
       this.fecha = fecha;
       this.borrado = borrado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estudiantesc getEstudiantesc() {
        return this.estudiantesc;
    }
    
    public void setEstudiantesc(Estudiantesc estudiantesc) {
        this.estudiantesc = estudiantesc;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }




}


