package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA



/**
 * Claseestudiante generated by hbm2java
 */
public class Claseestudiante  implements java.io.Serializable {


     private int id;
     private Clase clase;
     private Estudiante estudiante;
     private Boolean borrado;

    public Claseestudiante() {
    }

	
    public Claseestudiante(int id) {
        this.id = id;
    }
    public Claseestudiante(int id, Clase clase, Estudiante estudiante, Boolean borrado) {
       this.id = id;
       this.clase = clase;
       this.estudiante = estudiante;
       this.borrado = borrado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }




}


