package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private String codigo;
     private Profesor profesor;
     private Aula aula;
     private Catedra catedra;
     private String periodo;
     private Boolean borrado;
     private Set<ClaseEstudiante> claseEstudiantes = new HashSet<ClaseEstudiante>(0);

    public Clase() {
    }

	
    public Clase(String codigo) {
        this.codigo = codigo;
    }
    public Clase(String codigo, Profesor profesor, Aula aula, Catedra catedra, String periodo, Boolean borrado, Set<ClaseEstudiante> claseEstudiantes) {
       this.codigo = codigo;
       this.profesor = profesor;
       this.aula = aula;
       this.catedra = catedra;
       this.periodo = periodo;
       this.borrado = borrado;
       this.claseEstudiantes = claseEstudiantes;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Catedra getCatedra() {
        return this.catedra;
    }
    
    public void setCatedra(Catedra catedra) {
        this.catedra = catedra;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<ClaseEstudiante> getClaseEstudiantes() {
        return this.claseEstudiantes;
    }
    
    public void setClaseEstudiantes(Set<ClaseEstudiante> claseEstudiantes) {
        this.claseEstudiantes = claseEstudiantes;
    }




}


