package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String cedula;
     private Preinscrito preinscrito;
     private String numeroIns;
     private Date fechaIns;
     private Boolean borrado;
     private Set<ClaseEstudiante> claseEstudiantes = new HashSet<ClaseEstudiante>(0);

    public Estudiante() {
    }

	
    public Estudiante(String cedula, Preinscrito preinscrito) {
        this.cedula = cedula;
        this.preinscrito = preinscrito;
    }
    public Estudiante(String cedula, Preinscrito preinscrito, String numeroIns, Date fechaIns, Boolean borrado, Set<ClaseEstudiante> claseEstudiantes) {
       this.cedula = cedula;
       this.preinscrito = preinscrito;
       this.numeroIns = numeroIns;
       this.fechaIns = fechaIns;
       this.borrado = borrado;
       this.claseEstudiantes = claseEstudiantes;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Preinscrito getPreinscrito() {
        return this.preinscrito;
    }
    
    public void setPreinscrito(Preinscrito preinscrito) {
        this.preinscrito = preinscrito;
    }
    public String getNumeroIns() {
        return this.numeroIns;
    }
    
    public void setNumeroIns(String numeroIns) {
        this.numeroIns = numeroIns;
    }
    public Date getFechaIns() {
        return this.fechaIns;
    }
    
    public void setFechaIns(Date fechaIns) {
        this.fechaIns = fechaIns;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<ClaseEstudiante> getClaseEstudiantes() {
        return this.claseEstudiantes;
    }
    
    public void setClaseEstudiantes(Set<ClaseEstudiante> claseEstudiantes) {
        this.claseEstudiantes = claseEstudiantes;
    }




}


