package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private String cedula;
     private Preinscrito preinscrito;
     private String numeroins;
     private String fechains;
     private Boolean borrado;
     private Set<Claseestudiante> claseestudiantes = new HashSet<Claseestudiante>(0);

    public Estudiante() {
    }

	
    public Estudiante(String cedula) {
        this.cedula = cedula;
    }
    public Estudiante(String cedula,Preinscrito preinscrito,  String numeroins, String fechains, Boolean borrado, Set<Claseestudiante> claseestudiantes) {
       this.cedula = cedula;
       this.preinscrito=preinscrito;
       this.numeroins = numeroins;
       this.fechains = fechains;
       this.borrado = borrado;
       this.claseestudiantes = claseestudiantes;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public Preinscrito getPreinscrito() {
        return preinscrito;
    }

    public void setPreinscrito(Preinscrito preinscrito) {
        this.preinscrito = preinscrito;
    }
    
    
    
    public String getNumeroins() {
        return this.numeroins;
    }
    
    public void setNumeroins(String numeroins) {
        this.numeroins = numeroins;
    }
    public String getFechains() {
        return this.fechains;
    }
    
    public void setFechains(String fechains) {
        this.fechains = fechains;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Claseestudiante> getClaseestudiantes() {
        return this.claseestudiantes;
    }
    
    public void setClaseestudiantes(Set<Claseestudiante> claseestudiantes) {
        this.claseestudiantes = claseestudiantes;
    }




}


