package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantesc generated by hbm2java
 */
public class Estudiantesc  implements java.io.Serializable {


     private String carnet;
     private String nombres;
     private String apellidos;
     private String email;
     private String telefonos;
     private Integer horascumplidas;
     private Boolean borrado;
     private Set<Charlaplantel> charlaplantels = new HashSet<Charlaplantel>(0);

    public Estudiantesc() {
    }

	
    public Estudiantesc(String carnet, String nombres, String apellidos) {
        this.carnet = carnet;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Estudiantesc(String carnet, String nombres, String apellidos, String email, String telefonos, Integer horascumplidas, Boolean borrado, Set<Charlaplantel> charlaplantels) {
       this.carnet = carnet;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.telefonos = telefonos;
       this.horascumplidas = horascumplidas;
       this.borrado = borrado;
       this.charlaplantels = charlaplantels;
    }
   
    public String getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public Integer getHorascumplidas() {
        return this.horascumplidas;
    }
    
    public void setHorascumplidas(Integer horascumplidas) {
        this.horascumplidas = horascumplidas;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Charlaplantel> getCharlaplantels() {
        return this.charlaplantels;
    }
    
    public void setCharlaplantels(Set<Charlaplantel> charlaplantels) {
        this.charlaplantels = charlaplantels;
    }




}


