package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA



/**
 * Estudianterepresentante generated by hbm2java
 */
public class Estudianterepresentante  implements java.io.Serializable {


     private int id;
     private Representante representante;
     private Aspirante aspirante;
     private Boolean borrado;

    public Estudianterepresentante() {
    }

	
    public Estudianterepresentante(int id) {
        this.id = id;
    }
    public Estudianterepresentante(int id, Representante representante, Aspirante aspirante, Boolean borrado) {
       this.id = id;
       this.representante = representante;
       this.aspirante = aspirante;
       this.borrado = borrado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Representante getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(Representante representante) {
        this.representante = representante;
    }
    public Aspirante getAspirante() {
        return this.aspirante;
    }
    
    public void setAspirante(Aspirante aspirante) {
        this.aspirante = aspirante;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }




}


