package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private String nombre;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private String lugar;
     private Boolean borrado;
     private Set<ProveedoresEvento> proveedoresEventos = new HashSet<ProveedoresEvento>(0);

    public Evento() {
    }

	
    public Evento(String nombre) {
        this.nombre = nombre;
    }
    public Evento(String nombre, String descripcion, Date fechaInicio, Date fechaFin, String lugar, Boolean borrado, Set<ProveedoresEvento> proveedoresEventos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.lugar = lugar;
       this.borrado = borrado;
       this.proveedoresEventos = proveedoresEventos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<ProveedoresEvento> getProveedoresEventos() {
        return this.proveedoresEventos;
    }
    
    public void setProveedoresEventos(Set<ProveedoresEvento> proveedoresEventos) {
        this.proveedoresEventos = proveedoresEventos;
    }




}


