package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA



/**
 * Examenasisten generated by hbm2java
 */
public class Examenasisten  implements java.io.Serializable {


     private int id;
     private Preinscrito preinscrito;
     private Examen examen;
     private Float notaobtenida;
     private Boolean borrado;

    public Examenasisten() {
    }

	
    public Examenasisten(int id) {
        this.id = id;
    }
    public Examenasisten(int id, Preinscrito preinscrito, Examen examen, Float notaobtenida, Boolean borrado) {
       this.id = id;
       this.preinscrito = preinscrito;
       this.examen = examen;
       this.notaobtenida = notaobtenida;
       this.borrado = borrado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Preinscrito getPreinscrito() {
        return this.preinscrito;
    }
    
    public void setPreinscrito(Preinscrito preinscrito) {
        this.preinscrito = preinscrito;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Float getNotaobtenida() {
        return this.notaobtenida;
    }
    
    public void setNotaobtenida(Float notaobtenida) {
        this.notaobtenida = notaobtenida;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }




}


