package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private String codigo;
     private Aula aula;
     private String fecha;
     private String tipo;
     private Boolean borrado;
     private Set<Examenasisten> examenasistens = new HashSet<Examenasisten>(0);
     private Set<Examenapoyo> examenapoyos = new HashSet<Examenapoyo>(0);

    public Examen() {
    }

	
    public Examen(String codigo) {
        this.codigo = codigo;
    }
    public Examen(String codigo, Aula aula, String fecha, String tipo, Boolean borrado, Set<Examenasisten> examenasistens, Set<Examenapoyo> examenapoyos) {
       this.codigo = codigo;
       this.aula = aula;
       this.fecha = fecha;
       this.tipo = tipo;
       this.borrado = borrado;
       this.examenasistens = examenasistens;
       this.examenapoyos = examenapoyos;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Examenasisten> getExamenasistens() {
        return this.examenasistens;
    }
    
    public void setExamenasistens(Set<Examenasisten> examenasistens) {
        this.examenasistens = examenasistens;
    }
    public Set<Examenapoyo> getExamenapoyos() {
        return this.examenapoyos;
    }
    
    public void setExamenapoyos(Set<Examenapoyo> examenapoyos) {
        this.examenapoyos = examenapoyos;
    }




}


