package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA



/**
 * ExamenAsistenId generated by hbm2java
 */
public class ExamenAsistenId  implements java.io.Serializable {


     private String examen;
     private String preinscrito;

    public ExamenAsistenId() {
    }

    public ExamenAsistenId(String examen, String preinscrito) {
       this.examen = examen;
       this.preinscrito = preinscrito;
    }
   
    public String getExamen() {
        return this.examen;
    }
    
    public void setExamen(String examen) {
        this.examen = examen;
    }
    public String getPreinscrito() {
        return this.preinscrito;
    }
    
    public void setPreinscrito(String preinscrito) {
        this.preinscrito = preinscrito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExamenAsistenId) ) return false;
		 ExamenAsistenId castOther = ( ExamenAsistenId ) other; 
         
		 return ( (this.getExamen()==castOther.getExamen()) || ( this.getExamen()!=null && castOther.getExamen()!=null && this.getExamen().equals(castOther.getExamen()) ) )
 && ( (this.getPreinscrito()==castOther.getPreinscrito()) || ( this.getPreinscrito()!=null && castOther.getPreinscrito()!=null && this.getPreinscrito().equals(castOther.getPreinscrito()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExamen() == null ? 0 : this.getExamen().hashCode() );
         result = 37 * result + ( getPreinscrito() == null ? 0 : this.getPreinscrito().hashCode() );
         return result;
   }   


}


