package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private String codigo;
     private Aula aula;
     private Date fecha;
     private String tipo;
     private Boolean borrado;
     private Set<ExamenAsisten> examenAsistens = new HashSet<ExamenAsisten>(0);
     private Set<ExamenApoyo> examenApoyos = new HashSet<ExamenApoyo>(0);

    public Examen() {
    }

	
    public Examen(String codigo) {
        this.codigo = codigo;
    }
    public Examen(String codigo, Aula aula, Date fecha, String tipo, Boolean borrado, Set<ExamenAsisten> examenAsistens, Set<ExamenApoyo> examenApoyos) {
       this.codigo = codigo;
       this.aula = aula;
       this.fecha = fecha;
       this.tipo = tipo;
       this.borrado = borrado;
       this.examenAsistens = examenAsistens;
       this.examenApoyos = examenApoyos;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<ExamenAsisten> getExamenAsistens() {
        return this.examenAsistens;
    }
    
    public void setExamenAsistens(Set<ExamenAsisten> examenAsistens) {
        this.examenAsistens = examenAsistens;
    }
    public Set<ExamenApoyo> getExamenApoyos() {
        return this.examenApoyos;
    }
    
    public void setExamenApoyos(Set<ExamenApoyo> examenApoyos) {
        this.examenApoyos = examenApoyos;
    }




}


