package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA



/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private MensajeId id;
     private PersonalPio personalPio;
     private Usuario usuario;
     private Boolean leido;
     private String asunto;
     private Boolean borrado;

    public Mensaje() {
    }

	
    public Mensaje(MensajeId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Mensaje(MensajeId id, PersonalPio personalPio, Usuario usuario, Boolean leido, String asunto, Boolean borrado) {
       this.id = id;
       this.personalPio = personalPio;
       this.usuario = usuario;
       this.leido = leido;
       this.asunto = asunto;
       this.borrado = borrado;
    }
   
    public MensajeId getId() {
        return this.id;
    }
    
    public void setId(MensajeId id) {
        this.id = id;
    }
    public PersonalPio getPersonalPio() {
        return this.personalPio;
    }
    
    public void setPersonalPio(PersonalPio personalPio) {
        this.personalPio = personalPio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Boolean getLeido() {
        return this.leido;
    }
    
    public void setLeido(Boolean leido) {
        this.leido = leido;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }




}


