package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Personalapoyo generated by hbm2java
 */
public class Personalapoyo  implements java.io.Serializable {


     private String cedula;
     private String nombres;
     private String apellidos;
     private String email;
     private String telefonos;
     private Boolean borrado;
     

    public Personalapoyo() {
    }

	
    public Personalapoyo(String cedula, String nombres, String apellidos) {
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Personalapoyo(String cedula, String nombres, String apellidos, String email, String telefonos, Boolean borrado) {
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.telefonos = telefonos;
       this.borrado = borrado;
       
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    




}


