package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA



/**
 * PreinscritoCarreraId generated by hbm2java
 */
public class PreinscritoCarreraId  implements java.io.Serializable {


     private String preinscrito;
     private String carrera;

    public PreinscritoCarreraId() {
    }

    public PreinscritoCarreraId(String preinscrito, String carrera) {
       this.preinscrito = preinscrito;
       this.carrera = carrera;
    }
   
    public String getPreinscrito() {
        return this.preinscrito;
    }
    
    public void setPreinscrito(String preinscrito) {
        this.preinscrito = preinscrito;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PreinscritoCarreraId) ) return false;
		 PreinscritoCarreraId castOther = ( PreinscritoCarreraId ) other; 
         
		 return ( (this.getPreinscrito()==castOther.getPreinscrito()) || ( this.getPreinscrito()!=null && castOther.getPreinscrito()!=null && this.getPreinscrito().equals(castOther.getPreinscrito()) ) )
 && ( (this.getCarrera()==castOther.getCarrera()) || ( this.getCarrera()!=null && castOther.getCarrera()!=null && this.getCarrera().equals(castOther.getCarrera()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPreinscrito() == null ? 0 : this.getPreinscrito().hashCode() );
         result = 37 * result + ( getCarrera() == null ? 0 : this.getCarrera().hashCode() );
         return result;
   }   


}


