package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private String cedula;
     private Usuario usuario;
     private Date fechaIngreso;
     private String cargo;
     private Boolean borrado;
     private Set<ProfesorMateria> profesorMaterias = new HashSet<ProfesorMateria>(0);
     private Set<Clase> clases = new HashSet<Clase>(0);

    public Profesor() {
    }

	
    public Profesor(String cedula, Usuario usuario) {
        this.cedula = cedula;
        this.usuario = usuario;
    }
    public Profesor(String cedula, Usuario usuario, Date fechaIngreso, String cargo, Boolean borrado, Set<ProfesorMateria> profesorMaterias, Set<Clase> clases) {
       this.cedula = cedula;
       this.usuario = usuario;
       this.fechaIngreso = fechaIngreso;
       this.cargo = cargo;
       this.borrado = borrado;
       this.profesorMaterias = profesorMaterias;
       this.clases = clases;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<ProfesorMateria> getProfesorMaterias() {
        return this.profesorMaterias;
    }
    
    public void setProfesorMaterias(Set<ProfesorMateria> profesorMaterias) {
        this.profesorMaterias = profesorMaterias;
    }
    public Set<Clase> getClases() {
        return this.clases;
    }
    
    public void setClases(Set<Clase> clases) {
        this.clases = clases;
    }




}


