package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String rif;
     private String nombre;
     private String area;
     private String email;
     private String direccion;
     private String telefonos;
     private Boolean borrado;
     private Set<ProveedoresEvento> proveedoresEventos = new HashSet<ProveedoresEvento>(0);

    public Proveedor() {
    }

	
    public Proveedor(String rif) {
        this.rif = rif;
    }
    public Proveedor(String rif, String nombre, String area, String email, String direccion, String telefonos, Boolean borrado, Set<ProveedoresEvento> proveedoresEventos) {
       this.rif = rif;
       this.nombre = nombre;
       this.area = area;
       this.email = email;
       this.direccion = direccion;
       this.telefonos = telefonos;
       this.borrado = borrado;
       this.proveedoresEventos = proveedoresEventos;
    }
   
    public String getRif() {
        return this.rif;
    }
    
    public void setRif(String rif) {
        this.rif = rif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<ProveedoresEvento> getProveedoresEventos() {
        return this.proveedoresEventos;
    }
    
    public void setProveedoresEventos(Set<ProveedoresEvento> proveedoresEventos) {
        this.proveedoresEventos = proveedoresEventos;
    }




}


