package pojo;
// Generated Oct 18, 2011 12:37:12 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Representante generated by hbm2java
 */
public class Representante  implements java.io.Serializable {


     private String cedula;
     private String nombres;
     private String apellidos;
     private String lugartrabajo;
     private String telefonos;
     private String direccion;
     private String gradoestudio;
     private Boolean borrado;
     

    public Representante() {
    }

	
    public Representante(String cedula, String nombres, String apellidos) {
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Representante(String cedula, String nombres, String apellidos, String lugartrabajo, String telefonos, String direccion, String gradoestudio, Boolean borrado) {
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.lugartrabajo = lugartrabajo;
       this.telefonos = telefonos;
       this.direccion = direccion;
       this.gradoestudio = gradoestudio;
       this.borrado = borrado;
       
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getLugartrabajo() {
        return this.lugartrabajo;
    }
    
    public void setLugartrabajo(String lugartrabajo) {
        this.lugartrabajo = lugartrabajo;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getGradoestudio() {
        return this.gradoestudio;
    }
    
    public void setGradoestudio(String gradoestudio) {
        this.gradoestudio = gradoestudio;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    




}


