package pojo;
// Generated Oct 16, 2011 2:22:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String cedula;
     private String nombres;
     private String apellidos;
     private String email;
     private Boolean esAdmin;
     private Date fechaRegistro;
     private String telefonos;
     private Boolean borrado;
     private Set<Profesor> profesors = new HashSet<Profesor>(0);
     private Set<PersonalPio> personalPios = new HashSet<PersonalPio>(0);
     private Set<Mensaje> mensajes = new HashSet<Mensaje>(0);
     private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);

    public Usuario() {
    }

	
    public Usuario(String cedula) {
        this.cedula = cedula;
    }
    public Usuario(String cedula, String nombres, String apellidos, String email, Boolean esAdmin, Date fechaRegistro, String telefonos, Boolean borrado, Set<Profesor> profesors, Set<PersonalPio> personalPios, Set<Mensaje> mensajes, Set<Aspirante> aspirantes) {
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.esAdmin = esAdmin;
       this.fechaRegistro = fechaRegistro;
       this.telefonos = telefonos;
       this.borrado = borrado;
       this.profesors = profesors;
       this.personalPios = personalPios;
       this.mensajes = mensajes;
       this.aspirantes = aspirantes;
    }
   
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getEsAdmin() {
        return this.esAdmin;
    }
    
    public void setEsAdmin(Boolean esAdmin) {
        this.esAdmin = esAdmin;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }
    public Set<Profesor> getProfesors() {
        return this.profesors;
    }
    
    public void setProfesors(Set<Profesor> profesors) {
        this.profesors = profesors;
    }
    public Set<PersonalPio> getPersonalPios() {
        return this.personalPios;
    }
    
    public void setPersonalPios(Set<PersonalPio> personalPios) {
        this.personalPios = personalPios;
    }
    public Set<Mensaje> getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set<Mensaje> mensajes) {
        this.mensajes = mensajes;
    }
    public Set<Aspirante> getAspirantes() {
        return this.aspirantes;
    }
    
    public void setAspirantes(Set<Aspirante> aspirantes) {
        this.aspirantes = aspirantes;
    }




}


