package pojo;
// Generated Oct 19, 2011 2:02:31 AM by Hibernate Tools 3.2.1.GA



/**
 * Violenciaplantel generated by hbm2java
 */
public class Violenciaplantel  implements java.io.Serializable {


     private int id;
     private Plantel plantel;
     private String tipoviolencia;
     private String medioviolencia;
     private String causaviolencia;
     private String grupoagresor;
     private String grupovictima;
     private String consecuencias;
     private String medidastomadas;
     private Boolean borrado;

    public Violenciaplantel() {
    }

	
    public Violenciaplantel(int id) {
        this.id = id;
    }
    public Violenciaplantel(int id, Plantel plantel, String tipoviolencia, String medioviolencia, String causaviolencia, String grupoagresor, String grupovictima, String consecuencias, String medidastomadas, Boolean borrado) {
       this.id = id;
       this.plantel = plantel;
       this.tipoviolencia = tipoviolencia;
       this.medioviolencia = medioviolencia;
       this.causaviolencia = causaviolencia;
       this.grupoagresor = grupoagresor;
       this.grupovictima = grupovictima;
       this.consecuencias = consecuencias;
       this.medidastomadas = medidastomadas;
       this.borrado = borrado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public String getTipoviolencia() {
        return this.tipoviolencia;
    }
    
    public void setTipoviolencia(String tipoviolencia) {
        this.tipoviolencia = tipoviolencia;
    }
    public String getMedioviolencia() {
        return this.medioviolencia;
    }
    
    public void setMedioviolencia(String medioviolencia) {
        this.medioviolencia = medioviolencia;
    }
    public String getCausaviolencia() {
        return this.causaviolencia;
    }
    
    public void setCausaviolencia(String causaviolencia) {
        this.causaviolencia = causaviolencia;
    }
    public String getGrupoagresor() {
        return this.grupoagresor;
    }
    
    public void setGrupoagresor(String grupoagresor) {
        this.grupoagresor = grupoagresor;
    }
    public String getGrupovictima() {
        return this.grupovictima;
    }
    
    public void setGrupovictima(String grupovictima) {
        this.grupovictima = grupovictima;
    }
    public String getConsecuencias() {
        return this.consecuencias;
    }
    
    public void setConsecuencias(String consecuencias) {
        this.consecuencias = consecuencias;
    }
    public String getMedidastomadas() {
        return this.medidastomadas;
    }
    
    public void setMedidastomadas(String medidastomadas) {
        this.medidastomadas = medidastomadas;
    }
    public Boolean getBorrado() {
        return this.borrado;
    }
    
    public void setBorrado(Boolean borrado) {
        this.borrado = borrado;
    }




}


